### ISSUE TITLE
Add support for more resolution methods

### ISSUE THREAD

**Issue by jeff-winn** [autofac/Autofac.Extensions.DependencyInjection#18]
It would be extremely helpful if this extension to Autofac supported the other resolution methods available to Autofac rather than just the out-of-the-box support Microsoft wants to expose for their own purposes.

Specifically the following resolution operations from the context:

- ResolveKeyed
- ResolveNamed

As of right now with the out-of-the-box support with this API being limited to what Microsoft has expsed we end up having to expose the container around the application to gain access to these other resolution methods when we need them.

A couple implementation ideas:

- Creating a few new interfaces within this extension API specifically designed to handle resolving components using the previously mentioned resolution operations available to Autofac.
- Adding new extension methods to _IServiceProvider_ to access these new interfaces without needing to directly expose the IContainer or IComponentContext around the application code.

Love the API and thank you for your consideration!

**Comment by tillig** [comment]
The benefit of using the Microsoft abstraction is that libraries can reference _only_ the Microsoft.Extensions.DependencyInjection stuff, while apps are the only things that actually have Autofac (or Autofac.Extensions.DependencyInjection) references.

If using this in your app, you already have an Autofac reference, so doing this shouldn't matter:
`serviceProvider.GetService<ILifetimeScope>().ResolveKeyed(...)`
You could add that as an extension right in your own app.

On the other hand, if you're thinking about using it in a library as a way to "keep the Autofac references out" then it wouldn't work because the extensions would be part of the Autofac implementation of the Microsoft stuff and would never be able to be implemented by any backing container _other_ than Autofac.

Given the point of this particular library is to map Autofac into the conforming container Microsoft provides, adding Autofac-specific extensions sort of goes against the intent of the library. As such, I think we will not be adding these.

However, again, if you want to add such a thing to your app, or if you want to create and publish a library to NuGet that has those extensions, you are more than welcome to do either or both.
