### ISSUE TITLE
Add IServiceProviderFactory support

### ISSUE THREAD

**Issue by tillig** [autofac/Autofac.Extensions.DependencyInjection#2]
The Microsoft.Extensions.DependencyInjection project has added [a new `IServiceProviderFactory` concept](https://github.com/aspnet/DependencyInjection/issues/442) as of [this commit](https://github.com/aspnet/DependencyInjection/commit/cc814c61435491917804bb4502c87eb93efd3960) to allow for better integration with container-specific features and registrations.

**Comment by mderriey** [comment]
Is anything blocking this issue from progressing? I'd be happy to start a PR.

**Comment by tillig** [comment]
I think @alexmg is working on this now.

**Comment by mderriey** [comment]
OK, no problems. If that's not the case, please let me know, I'll be glad to give it a shot.

**Comment by alexmg** [comment]
I have implemented the `IServiceProviderFactory` and just need to add another package with some `IWebHostBuilder` extensions to wire things up from the hosting side. I'll upgrade `Autofac.Extensions.DependencyInjection` to the .csproj format too.

**Comment by hikalkan** [comment]
Hi,

I used this in ``public void ConfigureServices(IServiceCollection services)`` method:

````C#
            services.AddAutofac(builder =>
            {
                builder.RegisterType<MyClass>();
            });
````

But it does not hit the ``builder.RegisterType<MyClass>();`` line. Do you have an idea or how I should use ``IServiceProviderFactory`` feature?

**Comment by hikalkan** [comment]
Has anybody seen my question?

**Comment by hikalkan** [comment]
Sure. But actually the documentation does not tell how to use IServiceProviderFactory. But it's easy to understand how to use it. Are you using IServiceProviderFactory feature or just returning IServiceProvider from the ConfigureServices method?

**Comment by tillig** [comment]
_You_ don't use the provider factory. ASP.NET Core does. The first set of examples shows how.

**Comment by hikalkan** [comment]
I was expecting that ``AddAutofac()`` works in ConfigureServices in Startup class too. But I see that it only works while building the Host.

**Comment by hikalkan** [comment]
I created a sample project.

* This is not working here: https://github.com/hikalkan/samples/blob/master/AutofacMsDependencyIntegration/WebApplication1/Program.cs#L17
* It's working here as documented: https://github.com/hikalkan/samples/blob/master/AutofacMsDependencyIntegration/WebApplication1/Startup.cs#L22

But I expect the first approach should also work, because the method summary says it: https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/develop/src/Autofac.Extensions.DependencyInjection/ServiceCollectionExtensions.cs#L40

I hope it's clear now.
