### ISSUE TITLE
Should there be a derived class of ContainerBuilder implementing IServiceCollection

### ISSUE THREAD

**Issue by yepeekai** [autofac/Autofac.Extensions.DependencyInjection#31]
This is more a question...  I am looking at this and I wonder why ContainerBuilder (or a derived containerBuilder) doesn't implement IServiceCollection.  It would make it simpler in my opinion...  It would be there at the very beginning instead of switching from IServiceCollection to ContainerBuilder in the middle of DI setup.  My problem at the moment is that I have splitted DI resgistration by assembly and some needs IServiceCollection and some other needs ContainerBuilder.  I have to split the method in 2 parts instead of passing the containerBuilder and using it for both IServiceCollection registrations and ContainerBuilderRegistration.

**Comment by tillig** [comment]
Unfortunately I don't think this is going to happen for a few reasons.

- Maintenance complexity: Trying to maintain, test, and ensure that two different registration languages are working isn't something we can take on.
- `IServiceCollection` behaves like a collection; `ContainerBuilder` behaves like a builder. Builders are basically forward-only. Sort of like adding configuration providers to a `ConfigurationBuilder`, you can't go back into the `ConfigurationBuilder` and reorder things, search through the registrations, etc. Same with `AppBuilder` in ASP.NET Core - it's a pipeline being built, not just a collection. The `IServiceCollection` technically lets you get in there and really monkey with things. Add, remove, reorder, update, whatever. It's nice and flexible, but totally incompatible with the way `ContainerBuilder` works.

If this is something you'd be interested in, I encourage you to create a project, build it, and ship it as a separate NuGet package. That way you get the features you're looking for, we're not a bottleneck, and you can work with your consumers to deliver the best experience possible.

**Comment by wasabii** [comment]
@tillig I've been maintaining one of these for a couple years now, if you're interested. It allows multiple invocations of Populate, and supports the semantics required for Try* methods. If you're interested.

https://github.com/alethic/Cogito.Autofac/blob/master/Cogito.Autofac.DependencyInjection/ComponentRegistryServiceCollection.cs

**Comment by tillig** [comment]
Looks good! Sounds like folks can try that out of they're looking for this feature!

**Comment by wasabii** [comment]
@tillig So you're free to take it off my hands, of course. :) It does seem like something that naturally belongs here.

In terms of (2), it solves all that (except for one nuance).

In terms of (1), well, it's already built. But I understand it would be an additional ongoing tested component.

Otherwise, to anybody else, enjoy.

**Comment by tillig** [comment]
@wasabii I totally understand, but I think when people think about Autofac they think there's an organization with devs constantly and actively working and maintaining it and all the dependency libraries and all the features and everything. In reality, it's about two and a half people working unpaid in spare time. Until we get [more folks in here to _own_ things](https://www.paraesthesia.com/archive/2019/07/05/autofac-still-looking-for-owners/) (e.g., share the support burden, actively answer questions, actively address issues, etc.), we have to rely on the community to fill the gaps and own/maintain these extra packages.

We have a few things right now that "have been turned over to us" (like the [Moq integration](https://github.com/autofac/Autofac.Extras.Moq) and the [FakeItEasy integration](https://github.com/autofac/Autofac.Extras.FakeItEasy)) where... the folks remaining on the project don't actually know how it's _supposed to work_ because we don't _use it ourselves_. Makes it really hard to answer questions about whether something is a bug or functioning as designed; also challenging to determine, when it is a bug, what the actual behavior _should be_.

Anyway, I definitely appreciate the offer, and there may come a day some time in the future when we ping you about it or implement something similar here. Unfortunately, I don't see that happening for a while, so if you already have the library published and folks are able to use it, it's fine with me if it stays over with you for the time being.
