### ISSUE TITLE
Register Autofac modules in IServiceCollection

### ISSUE THREAD

**Issue by johnduhart** [autofac/Autofac.Extensions.DependencyInjection#35]
We have an ASP.NET Core application where 95% of all registrations are done using the `IServiceCollection` API. In cases where we need to use some of Autofac's advanced features, we end up creating an Autofac module, and then adding it to the `ConfigureContainer` method on our startup.

Rather than having to maintain a separate registration source for our dependencies, I'd like to suggest making it possible to register Autofac modules within the `IServiceCollection` that's used to populate the `ContainerBuilder`. If this is a Bad Idea:tm: let me know your thoughts.

**Comment by tillig** [comment]
I don't think we'll be implementing this for a few reasons that boil down to:

- The Microsoft.Extensions.DependencyInjection stuff is intentionally a lowest-common-denominator conforming container that multiple backing DI implementations need to support.
- This can very easily become a slippery slope of trying to implement every Autofac-specific feature in MS format.

The point of the MS DI framework is to provide a high-level abstraction, similar to a logging abstraction but for DI. It allows other framework components like ASP.NET Core to develop features against a lowest common denominator set of features and assume that they will work the same regardless of the backing DI implementation. It's sort of like an interface that Autofac and others have implemented. Thinking about it that way, from a Liskov substitution principle standpoint, we need to behave the same as everything else when folks use that interface. We can't really have "special meanings" for things because then it breaks that contract.

To enable use of container-specific features, that's why things like `ConfigureContainer` or `IServiceProviderFactory` exist. Use the abstractions in frameworks (ASP.NET Core, Identity Server) and in apps requiring additional special config that knows about the backing store, plug in as needed.

But let's say we do allow for some sort of module registration. For example, we special case around things that implement `Autofac.IModule` or whatever and assume that the intent there is to register the module.

First, that's not really a safe assumption. It sounds reasonable, but we have a lot of people out there doing a lot of complex things. It's this range of complex things that get us features like the ability to [create a specific tagged lifetime scope to serve as a sort of "pseudo-container" for an app](https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/a12726d7f5ac770ccfbf2e2b1329617353bdf6c8/test/Autofac.Extensions.DependencyInjection.Test/AutofacRegistrationTests.cs#L83) such that self-hosted apps can be both ASP.NET Core _and_ something else all sharing the same container for singletons. An app like that might actually register a bunch of `IModule` implementations at app startup and use those as plugins when creating the child scope for the ASP.NET app. It's hard to say, but a change like that could be pretty breaking.

Second, we have other extension mechanisms like registration sources. Should we do the same for those? [We just had a pull request to try to get module and source registration parity in core Autofac](autofac/Autofac#940), so that would suggest we should. Will that break folks?

Finally, while I may be falling subject to the slippery slope logical fallacy... this very well could be a slippery slope. How come we don't enable a special way to push dependency configuration into this? What about keyed object registration? Multitenancy? That stuff isn't entirely speculation; we have received a lot of requests to try and mimic full Autofac functionality in things like our MEF integration package as well as via configuration.

Using the configuration example in particular, we very intentionally haven't mimicked everything in core Autofac via configuration - there's not a lot of value in trying to write code-as-JSON or what-have-you. If folks need to do complex configuration, we recommend using modules and then using configuration to register the appropriate module/parameters.

Bringing that back to this... there's not a lot of value in trying to mimic core Autofac functionality in a lowest-common-denominator abstraction. It'd get confusing and in many cases would still require folks use the actual core Autofac stuff... just like folks can do a limited amount of logging configuration with Microsoft.Extensions.Logging but for richer functionality you'd still fall back to, say, Serilog coding. The escape hatches in this case are `ConfigureContainer` and `IServiceProviderFactory`.

Anyway, I hope that helps you understand why we wouldn't be putting this in. I'm sorry if that's not the answer you were hoping for. If it's something you'd want to write and maintain, you're free to release your own extension package with an alternative/extended Autofac + Microsoft.Extensions.DependencyInjection integration mechanism.
