### ISSUE TITLE
Feature Request: allow replacement of lifetime scope when registering Autofac as the IOC provider in aspnetcore applications.

### ISSUE THREAD

**Issue by zumwald** [autofac/Autofac.Extensions.DependencyInjection#46]
Autofac version: 4.8.1
Autofac.Extensions.DependencyInjection version: 4.3.0

Pertinent stack trace info:
`System.InvalidOperationException: Unable to resolve service for type 'Redacted.Redacted.Pipeline.IPipelineWebExecutor' while attempting to activate 'Redacted.Redacted.Controllers.AboutController'.`

Sample code:

```csharp
public class Program
{
    public static void Main(string[] args)
    {
        var builder = WebHost.CreateDefaultBuilder(args);
        builder.ConfigureServices(services =>
        {
            services.AddAutofac(builder => 
            {
                builder.RegisterAssemblyTypes(typeof(Program).Assembly)
                           .PublicOnly()
                           .AsSelf()
                           .InstancePerMatchingLifetimeScope("SomeRootScope");
            });
        });
        
        builder.Build().Run();
    }
}
```

**Comment by zumwald** [comment]
Apologies for the heavy redaction, but the TL;DR is that we register our types in a lifetime scope and since `AddAutofac()` doesn't know about that lifetime scope, the types cannot be resolved.

Would be super if `AddAutofac()` could accept an optional callback which provides the built `IContainer` and accepts an `ILifetimeScope` to use for creating the IServiceProvider.

**Comment by tillig** [comment]
Short term, if you [look at our docs for ASP.NET "Without ConfigureContainer" startup](https://autofac.readthedocs.io/en/latest/integration/aspnetcore.html#quick-start-without-configurecontainer) you'll see there is an option of creating your own `AutofacServiceProvider` manually. I'd recommend this if you need to have a child lifetime scope.

```c#
  public IServiceProvider ConfigureServices(IServiceCollection services)
  {
    services.AddMvc();
    var builder = new ContainerBuilder();
    builder.Populate(services);
    builder.RegisterType<MyType>().As<IMyType>();
    this.ApplicationContainer = builder.Build();
    return new AutofacServiceProvider(this.ApplicationContainer.BeginLifetimeScope("tagged"));
  }
```

**However, be aware this may not be possible in ASP.NET Core 3.0.** [A lot has changed](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio) in ASP.NET Core 3.0 especially in regards to hosting and startup of apps. [The `GenericHostBuilder` doesn't support creating your own `IServiceProvider` and only allows use of `IServiceProviderFactory`](https://github.com/aspnet/AspNetCore/issues/5149). They assume that the IServiceProviderFactory will handle providing the container building mechanism _and_ will build the container / `IServiceProvider`.

Trying to build a flexible container under the conforming container constraints put on by ASP.NET Core and the Microsoft.Extensions.DependencyInjection integration is... really challenging. I can't promise it will be possible to get done what you want to get done using the ASP.NET Core out-of-the-box hosting once ASP.NET Core 3.0 hits.

I did add this into #36, where we'll track and manage updating docs and code to support things for the new mechanism. Perhaps some nature of `AddAutofac` overloads may help, since that's how the factory attaches itself to ASP.NET Core... but, then, the innards of the actual factory itself assume - as ASP.NET Core does - that there's only one container for the app and that is controlled and populated entirely by the host.

Since it's part of #36 now, I'll close this issue.
