### ISSUE TITLE
Suggestion: Use .NETCoreApp-3.0 as target-framework

### ISSUE THREAD

**Issue by alsami** [autofac/Autofac.Extensions.DependencyInjection#49]
Since ASP.NET Core is the main use-case for this library and will only support .NET Core with version 3, I've asked myself if only supporting `netcoreapp3.0` would be enough in the future. 

My idea is to ditch `netstandard1.3` and `netstandard2.0` with the next major release and support of ASP.NET Core 3.0, which will introduce breaking changes anyway as described in #36.

CC @tillig @alexmg

**Comment by tillig** [comment]
ASP.NET Core is not the only use case, though, and since it's switched to a generic hosting model in ASP.NET Core 3, it even pushes that point - it's not just ASP.NET.

If there are ways to keep compatibility with the old stuff whilst also supporting the new, that'd be the best option. It may mean breaking changes, but _removing_ compatibility is a last resort.
