### ISSUE TITLE
Error in Login and Register Asp MVC5

### ISSUE THREAD

**Issue by feryt20** [autofac/Autofac.Extensions.DependencyInjection#71]
hi
I'm using Autofac5 with Microsoft Individual Authentication in MVC5  but I get this Error:System.NullReferenceException
Im Injecting this library with following link: https://github.com/Sina-Soltani/Parbad
please help me how do solve this problem

**Comment by tillig** [comment]
"How do I?" questions ("How do I integrate this other library properly?") are best asked [on Stack Overflow](https://stackoverflow.com). We're not application integration experts or software consultants here, and if you add the `autofac` tag _as well as other relevant tags_ on your question and give it a good title (more descriptive than "Error in Login and Register ASP MVC5" because that doesn't really tell me _what_ you're trying to do) over on Stack Overflow, then you have a community of thousands - if not millions? -  that can look at your question and help. Plus, all the folks who'd answer questions here are _also_ there.
