### ISSUE TITLE
netcoreapp1.1 No service for type 'Microsoft.AspNetCore.Mvc.ModelBinding.IModelMetadataProvider' has been registered

### ISSUE THREAD

**Issue by chanaka1** [autofac/Autofac.Extensions.DependencyInjection#8]
**netcoreapp1.1**

app.UseMvc(); throw a error 

"No service for type 'M**icrosoft.AspNetCore.Mvc.ModelBinding.IModelMetadataProvider**' has been registered"

**Comment by chanaka1** [comment]
@alexmg Any idea on this ?  I'm having trouble running my app on Dotnet Core 1.1.0

**Comment by tillig** [comment]
I've seen other projects with similar errors pop up. Usually it's because...

- The bin and obj folders need to be deleted (it needs to be a clean build)
- The other ASP.NET dependencies need to be updated to the latest, too, not just the target framework.

If you think you have found an error and you're sure you've followed the docs, built totally clean, and all your dependencies are updated, you should post a minimal repro so we can see it in action.

**Comment by tillig** [comment]
Also, please be patient. You only opened the issue not even a day ago. The two people on this project aren't paid support. We're doing our best and appreciate your understanding.

**Comment by chanaka1** [comment]
I understand. I will figure it out. Thanks.
