### ISSUE TITLE
IServiceScopeFactory should be a singleton; service scopes should not be nested

### ISSUE THREAD

**Issue by pengweiqhca** [autofac/Autofac.Extensions.DependencyInjection#83]
**Describe the bug**
If [AutofacServiceScopeFactory](https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/master/src/Autofac.Extensions.DependencyInjection/AutofacRegistration.cs#L97) is transient, that will not compatible with Ms DI.

**To reproduce**
``` C#
if (provider.GetService<IServiceScopeFactory>() == provider.GetService<IServiceScopeFactory>())
{
    //Ms DI.
}
else
{
    //Autofac
}
```

**Comment by tillig** [comment]
There is no contract or behavior requirement in the MS DI abstractions that the scope factory is a singleton. If you're relying on that, it's a flaw in your code's design. Microsoft actually provides a large set of tests to validate compatibility with the parts of the contract and behavior they require and on which developers rely. Autofac integration passes all of these tests and they're run on every build.

**Comment by pengweiqhca** [comment]
``` C#
var scope1 = rootProvider.CreateScope();
var scope2 = scope1.ServiceProvider.CreateScope();

scope1.Dispose();

scope2.ServiceProvider.GetRequiredService<ILogger<IServiceProvider>>(); //Autofac will get a exception.
```

**Comment by tillig** [comment]
Yup. [That happens with base Autofac, too.](https://autofaccn.readthedocs.io/en/latest/lifetime/disposal.html#child-scopes-are-not-automatically-disposed) If you create child scopes you're responsible for cleaning them up in the right order.

**Comment by pengweiqhca** [comment]
> Yup. [That happens with base Autofac, too.](https://autofaccn.readthedocs.io/en/latest/lifetime/disposal.html#child-scopes-are-not-automatically-disposed) If you create child scopes you're responsible for cleaning them up in the right order.

I want to create a new scope(a child scope of root scope) rather not a child scope of current scope(non-root scope).

**Comment by tillig** [comment]
If you need to hold a reference to the root service provider for the purpose of creating a child scope specifically from the root, that's something to solve in your code. Patterns like CommonServiceLocator may help. This is not a common use case and not something Autofac will address for you.

**Comment by rozbo** [comment]
Just like this
https://github.com/autofac/Autofac/issues/1084

and from here https://github.com/dotnet/aspnetcore/issues/31478

> IServiceScopeFactory is always a Singleton but the IServiceProvider can vary based on the lifetime of the containing class. So if you create a scope and resolve services from this scope, and any of those services take an IServiceProvider, it'll be the scoped one.

And, in MS doc

https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-6.0

```c#
[HttpGet("/fire-and-forget-3")]
public IActionResult FireAndForget3([FromServices]IServiceScopeFactory 
                                    serviceScopeFactory)
{
    _ = Task.Run(async () =>
    {
        await Task.Delay(1000);

        using (var scope = serviceScopeFactory.CreateScope())
        {
            var context = scope.ServiceProvider.GetRequiredService<ContosoDbContext>();

            context.Contoso.Add(new Contoso());

            await context.SaveChangesAsync();                                        
        }
    });

    return Accepted();
}
```

This will crash with serviceScopeFactory has been disposed


@tillig can you check it again please?

**Comment by alsami** [comment]
No statement regarding service-scope factory but regarding your code:

Instead of using `IServiceScopeFactory` you can use `IServiceProvider` and create a scope there.

```csharp
using var scope = _serviceProvider.CreateScope();
var someDep = scope.ServiceProvider.GetRequiredService<SomeDep>();
```

Side note: I still do hope that you don't use that kind of code during production :)

**Comment by alsami** [comment]
I don't think that's accurate for this specific case. Everytime a controller endpoint is hit a scope is created. That's why you get an object disposed exception. Your controller returns accepted while stuff is still running in the background but the scope to do so, is disposed.

**Comment by rozbo** [comment]
![image](https://user-images.githubusercontent.com/7907969/161096024-8b4010f2-6a58-4c7f-b067-9d2b7cf50803.png)

**Comment by alsami** [comment]
I just double checked. This behavior is indeed different but as @tillig already mentioned there is no definition / requirement by MS to do so.

So if you want to do the same thing, you can pretty much rely on `IServiceProvider` as described by me above.

It might be indeed something worth mentioning in the docs. But same goes for MS docs, they should mention that it is always a singleton for their implementation :)

I've added an issue in the [docs repository](https://github.com/autofac/Documentation/issues/155).

**Comment by tillig** [comment]
This looks like something I need to file with the .NET Core folks because their compatibility tests don't indicate that the service scope factory must be a singleton, which indicates there's actually a bug in the docs recommending this path and not necessarily a bug that Autofac has to fix. I'll link that issue when I get a chance to file it.

**Comment by tillig** [comment]
I filed an issue about this here: https://github.com/dotnet/runtime/issues/67391

**Comment by rozbo** [comment]
OK , Thank you for give great patience and help to me

**Comment by tillig** [comment]
I'm going to re-open this issue since it appears, from https://github.com/dotnet/runtime/issues/67391, that having the service scope factory be a singleton is expected; and that the regular MS DI container doesn't have nested scopes so they've written in the assumption that none of the conforming containers use nested scopes, either. There are no compatibility tests in place for this in [`Microsoft.Extensions.DependencyInjection.Specification.Tests`](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.DependencyInjection.Specification.Tests/) either, though it sounds like there's now an intention to add some.

Changing this in Autofac.Extensions.DependencyInjection is possible but I can't guarantee that it won't break someone who's using Autofac and assuming that scopes behave... like Autofac, in a nested manner. If we do change it, we'll also need to ensure the [`Autofac.AspNetCore.Multitenant`](https://github.com/autofac/Autofac.AspNetCore.Multitenant) bits get updated and continue to work as expected. That one might actually be more challenging since there's an `IServiceScopeFactory` that's a singleton-per-tenant rather than singleton at the global level.

I'll also update the title on the issue to describe what needs to change.

**Comment by tillig** [comment]
We need to decide if we're going to change the default behavior here to match the MS container or if we're going to make "flat-scopes, singleton `IServiceProviderFactory`" something you need to opt into.

**If we make it the default behavior**:

- It's a breaking change for folks assuming scope hierarchy for units of work.
- We need to determine if using the original hierarchical scope behavior is something we'll allow folks to opt into.

**If it's not the default behavior**:

- We don't break people, but we're not 100% compatible with the MS DI conforming container.
- We need to decide if you can opt into the MS DI behavior or if we offer some other workaround for creating a scope from the root container. (Note the "create a scope from the root" mechanism may be challenging in situations where folks are using a child lifetime scope as the "root," including the multitenant support.)

In either case, we need to update documentation to make note of the scope model around this so there's no confusion.

From a personal perspective, I'm _really not a fan_ of this flat-scope thing. I hear what folks are saying, and I see the one documentation example where things don't work the same, but I also know we're like five years down the road here and we've never hit an issue with this _except_ for that one doc example.

However, I recognize that there are expectations around this conforming container and we (and every other IoC dev team in the .NET space) already kinda lost that battle. When the issue initially came up there weren't any spec tests, there weren't any explicit explanations of behavior, and it was arguably something that could be dealt with on a per-container basis. Apparently there are now assumptions built into the framework (somewhere? where?) about this so it's less about per-container handling and more something MS forgot to document and test. Hence the change recently and the re-opening of the issue.

Given that, **I'm thinking we make the breaking change and switch the MS DI conforming behavior to be the default behavior.** If folks want to make nested lifetime scopes for units of work, switch to injecting `ILifetimeScope` instead of `IServiceScopeFactory` and make a nested lifetime scope directly using Autofac since that's apparently an Autofac-specific feature. Again, I don't _like it_, but it's the "rip the band-aid off and get it done" approach. No opt-in to backwards compat, no additional code to maintain and test.

Yay? Nay?

**Comment by pengweiqhca** [comment]
I think keep the behavior not change and add an option for users to switch to "flat-scopes".
I don't care about more one option, I only care about being able to turn "inherit-scopes" into "flat-scopes".
I am currently modifying the `IServiceScopeFactory` scope via reflection. 😂

**Comment by alistairjevans** [comment]
I'm with you @tillig; my vote is for breaking change, switch to a flat conforming hierarchy in this integration. If people want nested scopes, they've gone outside the (apparent) bounds of MSDI and should be using Autofac anyway.

**Comment by tillig** [comment]
I'll see about coming up with a PR shortly, maybe early next week. I'll go with breaking change since I don't really want to maintain codelines for "opt-in" or "opt-out."

**Comment by rozbo** [comment]
Yep, I agree @alistairjevans , if some people want nested scopes, they should use ILifetimeScope instead of IServiceScopeFactory, cause IServiceScopeFactory has obvious MSDI attribution, and should not has different implementations..

**Comment by tillig** [comment]
I added a [PR to update the spec tests in `dotnet/runtime`](https://github.com/dotnet/runtime/pull/68517). I've got similar failing tests in my `issue-83` branch in this repo so we'll have them regardless of how long it might take to get them into the main repo. I have not yet put the fix into my branch.

Further, I've updated the branch to test both through the service provider factory implementations _and_ through our `ContainerBuilder` extensions. That way if something changes such that we update the factory and not the direct container tests (or vice versa) we'll be able to catch it.
