### ISSUE TITLE
Dependency Injection support for Azure Functions V3 (IFunctionsHostBuilder)

### ISSUE THREAD

**Issue by ssunkari** [autofac/Autofac.Extensions.DependencyInjection#90]
**Is your feature request related to a problem? Please describe.**
I am struggling to find a way to integrate Autofac with Azure functions V3. There is no mention in the Microsoft docs about any 3rd party DI integration. I would like to use autofac multitenant and Keyed Resolution features in Azure functions, the default DI lacks supports for this.  
https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection

**Describe the solution you'd like**
Would love to see any development towards building an extension for Azure Functions that work with default DI just like it does today with web apps that implement IHost.

**Describe alternatives you've considered**
I have looked into third-party integrations using attribute bindings but is very immature and lots of custom code

Found below on Azure-functions Official Github repo too
https://github.com/Azure/azure-functions-host/issues/4429

**Comment by tillig** [comment]
A quick Google search [shows that the larger community appears to have bridged this gap](https://github.com/junalmeida/autofac-azurefunctions), which is cool because the few maintainers of core Autofac don't really have the bandwidth to take on a new integration package. I'd recommend checking that out to see how it goes.
